import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/cards/menu'
import About from '../components/cards/about'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rezero_Log</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className='display-3'>Rezero_Log</h1>
          
        </div>
        <p className='text-danger display-6'>現在準備中です。</p>
        <About></About>
        <Menu></Menu>
      </main>
    </>
  )
}
